

run_1.sem:
	gcc -std=c17 ./1.sem.c -o build/1.sem -g && ./build/1.sem

run_2.sem:
	gcc -std=c17 ./2.sem_pthread.c -lpthread -o build/2.sem_pthread -g && ./build/2.sem_pthread

run_3.shm:
	gcc -std=c17 ./3.shm.c -o build/3.shm -g && ./build/3.shm

run_4.sem_lab:
	gcc -std=c17 ./4.1.sem_lab.c -o build/4.1.sem_lab -g && ./build/4.1.sem_lab

