

run1.three:
	gcc -std=c17 ./1.threelab.c -o build/1.threelab -g && ./build/1.threelab

run2.three:
	gcc -std=c17 ./2.threelab.c -o build/2.threelab -g && ./build/2.threelab

run3.three:
	gcc -std=c17 ./3.threelab.c -o build/3.threelab -g && ./build/3.threelab
