

run1.two:
	gcc -std=c17 ./1.twolab.c -o build/1.twolab -g && ./build/1.twolab

run2.two:
	gcc -std=c17 ./2.twolab.c -o build/2.twolab -g && ./build/2.twolab

run3.two:
	gcc -std=c17 ./3.twolab.c -o build/3.twolab -g && ./build/3.twolab

run4.two:
	gcc -std=c17 ./4.twolab.c -o build/4.twolab -g && ./build/4.twolab

run5.two:
	gcc -std=c17 ./5.twolab.c -o build/5.twolab -g && ./build/5.twolab
