

run1.two:
	gcc -std=c17 ./1.twolab.c -o build/1.twolab -g && ./build/1.twolab

run2.two:
	gcc -std=c17 ./2.twolab.c -o build/2.twolab -g && ./build/2.twolab

run3.two:
	gcc -std=c17 ./3.twolab.c -o build/3.twolab -g && ./build/3.twolab

run4.two:
	gcc -std=c17 ./4.twolab.c -o build/4.twolab -g && ./build/4.twolab

run5.two:
	gcc -std=c17 ./5.twolab.c -o build/5.twolab -g && ./build/5.twolab

run1.lab:
	gcc -std=c17 ./1.lab.c -o build/1.lab -g && ./build/1.lab
run2.lab:
	gcc -std=c17 ./2.lab.c -o build/2.lab -g && ./build/2.lab
run3.lab:
	gcc -std=c17 ./3.lab.c -o build/3.lab -g && ./build/3.lab
run3.fileone:
	gcc -std=c17 ./3.fileone.c -o build/3.fileone -g && ./build/3.fileone
run3.filetwo:
	gcc -std=c17 ./3.filetwo.c -o build/3.filetwo -g && ./build/3.filetwo
run3.1.lab:
	gcc -std=c17 ./3.1.lab.c -o build/3.1.lab -g && ./build/3.1.lab